### ISSUE TITLE
Using a Trained model

### ISSUE THREAD

**Issue by leifsyliongka** [mnuke/tf-slim-mnist#2]
Hello,

Nice tutorial, and thanks for writing it. I have a question. 
Assuming that I already have a trained model saved in a checkpoint, how do I now use that model and apply it? Like, in your tutorial how do I use my trained MNIST model and feed in a new set of MNIST images, and print the predictions?

Thank you.

**Comment by mnoukhov** [comment]
You restore the model and just run examples on it, [the page for tensorflow slim](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/slim#fine-tuning-existing-models) explains it well
